### ISSUE TITLE
Concurrent task running into directory already created.

### ISSUE THREAD

**Issue by toblender** [sindresorhus/grunt-concurrent#18]
Not sure if this is a concurrent task issue:

Running "concurrent:dist" (concurrent) task
    Reading target file...
        New Shard Created.
        Warning: Running "htmlmin:dist" (htmlmin) task
    Warning: Unable to create directory "/website/dist" (Error code: EEXIST). Use --force to continue.

```
Aborted due to warnings. Use --force to continue.
```

---

We have grunt building in maven, sometimes it's htmlmin sometimes it's imagemin that runs into this error.

**Comment by guss77** [comment]
It seems like a generic problem that occurs when using concurrent with many grunt tasks. Basically grunt generates destination paths for some very common use cases, and looks like the logic for that in grunt itself doesn't handle concurrency correctly.

This is probably not a problem in `grunt-concurrent` itself, and should be fixed in grunt proper.

**Comment by guss77** [comment]
The problem is here: https://github.com/gruntjs/grunt/blob/2ddec56192ba6599cd3aeb0dc812f54cfe83c07b/lib/grunt/file.js#L200 . The fix should be to have grunt ignore EEXISTS in that case.
