### ISSUE TITLE
Concurrent tasks losing the grunt.config context

### ISSUE THREAD

**Issue by guncha** [sindresorhus/grunt-concurrent#54]
It seems like tasks started via concurrent don't have access to the parent config vars. 

```js
grunt.registerTask('server', function () {
    grunt.config.set('HOST', 'lvh.me:3000');
    grunt.task.run([
      'concurrent:xyz'
    ]);
  });
```

The task `xyz` will not have access to the HOST variable. If the task is run without concurrent, it works fine. Maybe this is by design, I'm not sure, but it's sure unexpected.

**Comment by kevva** [comment]
What happens if you set it outside the task?

**Comment by guncha** [comment]
It works as expected.

**Comment by kevva** [comment]
Alright, as expected then. If you really need to set it inside you could try:

```js
grunt.registerTask('server', function () {
    grunt.config.set('HOST', 'lvh.me:3000');
    grunt.task.run([
        'concurrent:xyz'
    ]);
}.bind(grunt));
```

**Comment by guncha** [comment]
The behaviour still differs when a task is run with `concurrent` vs without.

**Comment by wardpeet** [comment]
Exactly I have kinda the same problem. We have a pretty complex build file and we were looking to make it concurrent. We build our system through teamcity to our different areas (preview,test,production). We do this by the command 'grunt teamcity' which than does 3 exec calls but with concurrent the tasks are not available.

I could rewrite parts of our grunt file but i doubt that it will fix it. I think the problem is the concurrent exec call?

```javascript
grunt.registerTask('teamcity', function() {
        grunt.loadNpmTasks('grunt-exec');
        grunt.loadNpmTasks('grunt-concurrent');
        grunt.initConfig({
            concurrent: {
                test: ['exec:test'],
                test: ['exec:preview'],
                test: ['exec:production']
            },
            exec: {
                test: { command: 'grunt build:teamcity:first:test:' + this.args.join(':') },
                preview: 'grunt build:teamcity:preview:' + this.args.join(':'),
                production: 'grunt build:teamcity:production:' + this.args.join(':')
            }
        });
        grunt.task.run(['concurrent:test','concurrent:preview','concurrent:production']);
    });
```

**Comment by sindresorhus** [comment]
That's unfortunately a limitation of spawning. Since the `server` task isn't run in the spawned gruntfile, the config is never set there. This could potentially be possible if grunt supported setting `config` from the command-line like it does flags. Then we could pass all the existing config down to the child process. (Maybe open a grunt issue about this? ;)). You could still do this manually though. In your gruntfile, stringify all the config, set it in a flag (which is passed to the child process), then have a check in the gruntfile to parse the flag and set the config.

**Comment by wardpeet** [comment]
Thanks @sindresorhus that seems to work, however i'm now using grunt-parallel to fix my issue because  i'm just need my exec calls to run side by side.

**Comment by Blasz** [comment]
Could this limitation be documented somewhere other than a closed issue?
