### ISSUE TITLE
Concurrent output logs not colorized

### ISSUE THREAD

**Issue by phairoh** [sindresorhus/grunt-concurrent#70]
When using logConcurrentOutput = true, the text for the logs are not colorized.  This seems to be a result of the change to piping to stdout as changing the code back to the former way fixes the issue.

Reproduction steps:
1. Create node project utilizing `npm install debug` and create some debug output
2. Run project via grunt-concurrent and grunt-nodemon with env variable DEBUG=*
3. Observe output to stdout

I've seen this behavior through putty and mobaXterm running on Windows while using SSH to connect to a linux machine running Red Hat Enterprise 6.2.  I have not tested this on other systems.

**Comment by Riobe** [comment]
I just locked my dependency on grunt-concurrent to 1.0.1 and did:
`npm uninstall grunt-concurrent`
`npm install`

Now my colors show up again. I'll upgrade to current grunt-concurrent when I see that this issue has been fixed. (thanks for making this module)

**Comment by sindresorhus** [comment]
I don't have time to look into this right now, but a failing test would help move this forward faster.

**Comment by oxynad** [comment]
Same issue here.

**Comment by simonKon** [comment]
Same with 2.0.3. 
Would be nice to have a fix for that to keep dependencies up to date.
Right now i also reverting to 1.0.1

**Comment by pgrodrigues** [comment]
Yep I also have to use 1.0.1 otherwise winston logs won't be colorized.

**Comment by rbaconxc** [comment]
Same issue with 2.0.3 as well.  Also reverting to 1.0.1.

**Comment by fatfisz** [comment]
I have grunt-concurrent 2.0.3 on Windows 10, with `logConcurrentOutput: true` (even with DEBUG=*) and colors work just fine.

People, sindresorhus already knows that something doesn't work for someone, so maybe instead of the next "it doesn't work for me, revert to 1.0.1" post try looking into the problem yourself? Look a couple of posts before, he gave an idea of what would be the best to do.

**Comment by fatfisz** [comment]
I noticed that some of the tasks were having problems with colors after all, but it is a bit strange - `grunt-nodemon` works without problem, `grunt-contrib-watch` too, but `grunt-eslint` that's fired by `grunt-contrib-watch` lost colors.

I've delved deeper and found out that the `chalk` lib used in `grunt-eslint` is probably the problematic one. I've added two lines to the `eslint` task:
```js
console.log(chalk.red('hey'));
console.log('hey'.red);
```
The first one didn't work, but the second one was ok (so the `colors` lib works here).

I'll continue checking what's wrong and hopefully find where the problem lies.

**Comment by fatfisz** [comment]
I know what's going on, @sindresorhus.

`chalk` uses `supports-color` for deciding whether to support colors or not. `support-color` returns `false` because of this check: `if (process.stdout && !process.stdout.isTTY)`.

It seems that this could be resolved by slightly modifying the line
```js
var flags = grunt.option.flags(); 
```
to check if `flags` contain `--no-color`, and adding `--color` (which is a default option in grunt) if it's missing.

The `--color` flag could also be added regardless of whether there is the `--no-color` flag, because `supports-color` checks the presence of the `--no-color` flag first. I don't know if it's good however, because that's relying on the internals of the `supports-color` lib, and we don't know how other libs may behave.

--
As a temporary measure, running `grunt` with the `--color` flag, or including `grunt.option('color', true)` in `Gruntfile.js` works fine.

**Comment by fatfisz** [comment]
Oh, and I can create a PR, just tell me.

**Comment by sindresorhus** [comment]
Sure, PR welcome.

**Comment by jnovack** [comment]
grunt-concurrent@2.1.0 does not work for me or there is an additional issue (OSX, nodejs v0.12.2).

The interesting piece here is that concurrent is modifying my console, notice that it indents my window.   When I print a full width console line, the `nodemon only` it will print across the entire width.  However, the `concurrent` run will indent 4 spaces, and print a 70-space width line.

```
Running nodemon:
[jnovack@nodebox ~/Source/test]$ grunt runonly
Running "nodemon:dev" (nodemon) task
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js modules/***/*
[nodemon] starting `node --debug index.js`
Debugger listening on port 5858
Initializing...
############################################################################################################################################################
  module:network loaded successfully. +0ms 
```

Running concurrent:
```
[jnovack@nodebox ~/Source/test]$ grunt --color
Running "concurrent:dev" (concurrent) task
    Running "watch" task
    Waiting...
    Running "nodemon:dev" (nodemon) task
    [nodemon] 1.8.1
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: index.js modules/***/*
    [nodemon] starting `node --debug index.js`
    Debugger listening on port 5858
    Initializing...
    ######################################################################
    Wed, 09 Dec 2015 16:25:07 GMT module:network loaded successfully.
```

**Comment by ohjames** [comment]
@jnovack same for me, it still isn't working in linux (even with `grunt.option('color', true)`).

It indents stdout for me but only when it comes from the same process, if you `spawn` something the output is not indented. Suggests to me it's overwriting `console.log`.
