### ISSUE TITLE
Lost debug colors with new version.

### ISSUE THREAD

**Issue by jackspaniel** [sindresorhus/grunt-concurrent#86]
After some detective work I finally isolated why were weren't seeing colored debug output from debug js (https://www.npmjs.com/package/debug). The problem was in upgrading to a newer version of grunt concurrent. On 0.4.2 debug works fine with colored output, whereas on 2.1.0 we don't see colored output.

The problem is this code in lib/debug.js:
```
    var tty = require('tty');
    var isatty = tty.isatty(2);
```

When running our node app with the older version of grunt-concurrent, isatty is true. Whereas with the newer version, isatty is false. Is there some setting I can change in grunt-concurrent to get tty.isatty(2) to return true?

**Comment by fatfisz** [comment]
Unfortunately, not much.
You could always ask maintainers of `debug` to honor the `--color` flag. Or, if I'm not mistaken, you could set the `DEBUG_COLORS` to something sensible (see: https://github.com/visionmedia/debug/blob/master/node.js#L44).

Relying on the `tty.isatty` method sometimes is not enough, for example when you use some intermediary streams (as it is in the case of `grunt-concurrent`). That's why you should always look for some kind of an env var (like `DEBUG_COLORS`) or a parameter (like `--color`) when the colors aren't working.

**Comment by jackspaniel** [comment]
Ok, yeah it looks like the DEBUG_COLORS environment variable will work on their end. I'll let them know it's broken out of the box with latest grunt-concurrent. Thanks.

**Comment by eces** [comment]
Thanks. `DEBUG_COLORS=1 grunt serve`
