### ISSUE TITLE
Fails to run targets with string keys

### ISSUE THREAD

**Issue by raddevon** [sindresorhus/grunt-concurrent#87]
With this config:

``` javascript
    concurrent: {
      options: {
        logConcurrentOutput: true
      },
      debug: ['server:debug', 'node-inspector'],
      'debug:production': ['server:debug:production', 'node-inspector'],
      'debug:slack': ['server:debug:slack', 'node-inspector'],
      test: ['jasmine_nodejs', 'shell:chimp']
    },
```

`grunt concurrent:debug:production` instead runs `concurrent:debug`. I've changed the config to

``` javascript
    concurrent: {
      options: {
        logConcurrentOutput: true
      },
      staging: ['server:debug', 'node-inspector'],
      production: ['server:debug:production', 'node-inspector'],
      slack: ['server:debug:slack', 'node-inspector'],
      test: ['jasmine_nodejs', 'shell:chimp']
    },
```

and `grunt concurrent:production` works as expected.

**Comment by DominguesGM** [comment]
Hey! I'll be looking into this issue, if that's ok.

If you don't mind, I'd like to ask a question. From what I understand, grunt does not allow for nested tasks. I was trying to replicate the issue and I realized it didn't solely occur within the 'concurrent' task, but also with any other task defined similarly (two colons). Wouldn't this make it a grunt issue rather than a grunt-concurrent issue? Or have you seen other cases of grunt tasks where using more than one colon works correctly?

It seems like grunt is simply discarding any other input that appears after a second colon.
